apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "v1.16.3"
dependencies:
  - name: cert-manager
    version: v1.16.3
    repository: https://charts.jetstack.io