airflow:
  executor: "LocalExecutor"  
  fernetKey: ""
  webserverSecretKey: ""
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false

  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false

  flower:
    enabled: false
  statsd:
    enabled: false
  redis:
    enabled: false

  ingress:
    apiServer:
      enabled: true
      ingressClassName: traefik
      hosts:
        - airflow.localhost
      path: /
      tls:
        enabled: false         # flip to true once you add certs
