airflow:
  executor: "LocalExecutor"  
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false

  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false

  flower:
    enabled: false
  statsd:
    enabled: false


  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: false

  ingress:
    web:
      enabled: true
      ingressClassName: traefik
      hosts:
        - airflow.localhost          # pick any host-name you like
      path: /
      tls:                       # simple HTTP for local work; flip to true once you have TLS certs
        enabled: false