apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-server-ingress
  namespace: {{ .Release.Namespace }}
  # We remove all old annotations, especially kubernetes.io/ingress.class
  # and any cert-manager or TLS related ones.
  # You can add other Traefik-specific annotations here if needed later.
  annotations: {}
spec:
  # This is the correct, modern way to specify the ingress controller.
  ingressClassName: traefik
  rules:
  - host: argocd.localhost # Or whatever host you have in your values.yaml
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # The service name is typically constructed from the release name
            name: {{ .Release.Name }}-argocd-server
            port:
              number: 80
# The entire 'tls:' section has been removed for a plain HTTP setup.