apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-server-ingress
  namespace: argo-cd
  annotations:
    # argocd.argoproj.io/sync-wave: "1"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: argo-cd.dev.philipsolarz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              name: https
  tls:
  - hosts:
    - argo-cd.dev.philipsolarz.com
    secretName: argo-cd-server-tls # as expected by argo-cd-server