minio:
  mode: standalone
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path

  service:
    type: LoadBalancer          # k3s’ klipper-lb
    ports:
      api: 9000
      console: 9001

  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: s3.minio.localhost      # API endpoint
        paths:
          - path: /
            pathType: Prefix
            service:
              name: minio
              port:
                name: api
      - host: console.minio.localhost # Web console
        paths:
          - path: /
            pathType: Prefix
            service:
              name: minio
              port:
                name: console

  env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://console.minio.localhost"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
