minio:
  mode: standalone
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path

  service:
    type: LoadBalancer
    port: 9000          # S3 / API

  consoleService:
    type: LoadBalancer
    port: 9001          # Web console

  # --- Ingress for the API --------------------------------------------------
  ingress:
    enabled: true
    ingressClassName: traefik
    path: /
    hosts:
      - s3.minio.localhost   # <- **string**, not map
    tls: []                  # add a secret here if you terminate TLS

  # --- Ingress for the console ---------------------------------------------
  consoleIngress:
    enabled: true
    ingressClassName: traefik
    path: /
    hosts:
      - console.minio.localhost

  env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://console.minio.localhost"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
