apiVersion: v2
name: tempo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "2.8.1"
dependencies:
  - name: tempo-distributed
    version: 1.23.2
    repository: https://grafana.github.io/helm-charts
