mimir-distributed:

  minio:
    enabled: false

  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: minio.minio.svc.cluster.local:9000
            region: us-east-1
            access_key_id: minio
            secret_access_key: minio123
            insecure: true

      distributor:
        ring:
          replication_factor: 1

      ingester:
        ring:
          replication_factor: 1

      store_gateway:
        sharding_ring:
          replication_factor: 1

      ruler:
        sharding_ring:
          replication_factor: 1

      alertmanager:
        sharding_ring:
          replication_factor: 1

      blocks_storage:
        s3:
          bucket_name: mimir-tsdb
      ruler_storage:
        s3:
          bucket_name: mimir-ruler
      alertmanager_storage:
        s3:
          bucket_name: mimir-alerts

  distributor:      { replicas: 1 }
  ingester:         { replicas: 1 }
  querier:          { replicas: 1 }
  query_frontend:   { replicas: 1 }
  store_gateway:    { replicas: 1 }
  compactor:        { replicas: 1 }
  alertmanager:     { replicas: 1 }
  ruler:            { replicas: 1 }

  chunks-cache:     { enabled: false }
  index-cache:      { enabled: false }
  metadata-cache:   { enabled: false }
  results-cache:    { enabled: false }
  admin-cache:      { enabled: false }

  gateway:
    enabledNonEnterprise: true
    replicas: 1
