apiVersion: v2
name: argo-cd
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "v2.13.3"
dependencies:
  - name: argo-cd
    version: 7.7.16
    repository: https://argoproj.github.io/argo-helm