argo-cd:
  global:
    domain: argocd.localhost
  configs:
    params:
      controller.repo.server.plaintext: "true"
      dexserver.disable.tls: "true"
      server.dex.server.plaintext: "true"
      server.insecure: "true"
      server.repo.server.plaintext: "true"
  server:
    ingress:
      enabled: true