opentelemetry-collector:
  mode: "daemonset"
  image:
    repository: otel/opentelemetry-collector-contrib
  config:
    exporters:
      otlp/loki:
        endpoint: "loki-gateway.observability.svc.cluster.local:80"
        tls:
          insecure: true
      otlp/mimir:
        endpoint: "mimir-gateway.observability.svc.cluster.local:80"
        tls:
          insecure: true
      otlp/tempo:
        endpoint: "tempo-gateway.observability.svc.cluster.local:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/loki]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/mimir]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/tempo]